#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vim
Version  : 8.2.3605
Release  : 1775
URL      : https://github.com/vim/vim/archive/v8.2.3605/vim-8.2.3605.tar.gz
Source0  : https://github.com/vim/vim/archive/v8.2.3605/vim-8.2.3605.tar.gz
Summary  : A highly configurable, improved version of the vi text editor
Group    : Development/Tools
License  : LGPL-2.1 MIT Vim
Requires: vim-bin = %{version}-%{release}
Requires: vim-data = %{version}-%{release}
Requires: vim-filemap = %{version}-%{release}
Requires: vim-license = %{version}-%{release}
Requires: vim-man = %{version}-%{release}
Requires: usrbinvi
BuildRequires : acl-dev
BuildRequires : attr-dev
BuildRequires : elfutils-dev
BuildRequires : gmp-dev
BuildRequires : gpm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : python3-dev
BuildRequires : usrbinvi
Patch1: 0001-Add-patch-for-stateless.patch
Patch2: 0002-add-clearlinux-vimrc-file.patch

%description
Vim is a highly configurable text editor for efficiently creating and changing
any kind of text. It is included as "vi" with most UNIX systems and with Apple
OS X. Among its features are: persistent, multi-level undo tree; extensive
plugin system; support for hundreds of programming languages and file formats;
powerful search and replace; integrates with many tools.

%package bin
Summary: bin components for the vim package.
Group: Binaries
Requires: vim-data = %{version}-%{release}
Requires: vim-license = %{version}-%{release}
Requires: vim-filemap = %{version}-%{release}

%description bin
bin components for the vim package.


%package data
Summary: data components for the vim package.
Group: Data

%description data
data components for the vim package.


%package extras-minimal
Summary: extras-minimal components for the vim package.
Group: Default

%description extras-minimal
extras-minimal components for the vim package.


%package filemap
Summary: filemap components for the vim package.
Group: Default

%description filemap
filemap components for the vim package.


%package license
Summary: license components for the vim package.
Group: Default

%description license
license components for the vim package.


%package man
Summary: man components for the vim package.
Group: Default

%description man
man components for the vim package.


%prep
%setup -q -n vim-8.2.3605
cd %{_builddir}/vim-8.2.3605
%patch1 -p1
%patch2 -p1
pushd ..
cp -a vim-8.2.3605 buildavx2
popd

%build
## build_prepend content
# build vim-minimal
%configure --with-features=tiny --enable-perlinterp=no --enable-pythoninterp=no \
--enable-python3interp=no --enable-rubyinterp=no --enable-luainterp=no \
--with-vim-name=vim-minimal --enable-gui=no
make -C src %{?_smp_mflags}
mv src/vim-minimal ./
make distclean
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637085469
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
%configure --disable-static --with-features=huge \
--with-tlib=ncurses \
--enable-gtk2-check \
--enable-gui=gtk2 \
--enable-cscope \
--enable-multibyte \
--enable-luainterp \
--enable-pythoninterp \
--enable-cscope \
--enable-python3interp \
--enable-gpm
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
## build_prepend content
# build vim-minimal
%configure --with-features=tiny --enable-perlinterp=no --enable-pythoninterp=no \
--enable-python3interp=no --enable-rubyinterp=no --enable-luainterp=no \
--with-vim-name=vim-minimal --enable-gui=no
make -C src %{?_smp_mflags}
mv src/vim-minimal ./
make distclean
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static --with-features=huge \
--with-tlib=ncurses \
--enable-gtk2-check \
--enable-gui=gtk2 \
--enable-cscope \
--enable-multibyte \
--enable-luainterp \
--enable-pythoninterp \
--enable-cscope \
--enable-python3interp \
--enable-gpm
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1637085469
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vim
cp %{_builddir}/vim-8.2.3605/LICENSE %{buildroot}/usr/share/package-licenses/vim/100dd019c7d2912226c94666cac0f93eeb82a518
cp %{_builddir}/vim-8.2.3605/src/libvterm/LICENSE %{buildroot}/usr/share/package-licenses/vim/9979f112bdecefd99762f24f6af76972c2a3a1a6
cp %{_builddir}/vim-8.2.3605/src/xdiff/COPYING %{buildroot}/usr/share/package-licenses/vim/65c71b7ff77a59a32247d83a528728637263c1b5
cp %{_builddir}/vim-8.2.3605/src/xpm/COPYRIGHT %{buildroot}/usr/share/package-licenses/vim/553dde2683f711f77fe79504be0429256223469d
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/share/applications/gvim.desktop
rm -f %{buildroot}*/usr/share/applications/vim.desktop
rm -f %{buildroot}*/usr/share/icons/hicolor/48x48/apps/gvim.png
rm -f %{buildroot}*/usr/share/icons/locolor/16x16/apps/gvim.png
rm -f %{buildroot}*/usr/share/icons/locolor/32x32/apps/gvim.png
rm -f %{buildroot}*/usr/share/vim/vim*/autoload/go/def_test.vim
rm -f %{buildroot}*/usr/share/vim/vim*/autoload/go/fmt_test.vim
rm -f %{buildroot}*/usr/share/vim/vim*/autoload/go/test-fixtures/def/jump.go
rm -f %{buildroot}*/usr/share/vim/vim*/autoload/go/test-fixtures/fmt/hello.go
rm -f %{buildroot}*/usr/share/vim/vim*/autoload/go/test-fixtures/fmt/hello_golden.go
rm -f %{buildroot}*/usr/share/vim/vim*/compiler/go.vim
rm -f %{buildroot}*/usr/share/vim/vim*/ftplugin/asm.vim
rm -f %{buildroot}*/usr/share/vim/vim*/ftplugin/go.vim
rm -f %{buildroot}*/usr/share/vim/vim*/indent/go.vim
rm -f %{buildroot}*/usr/share/vim/vim*/syntax/go.vim
rm -f %{buildroot}*/usr/share/vim/vim*/ftplugin/meson.vim
rm -f %{buildroot}*/usr/share/vim/vim*/indent/meson.vim
rm -f %{buildroot}*/usr/share/vim/vim*/syntax/meson.vim
rm -f %{buildroot}*/usr/share/vim/vim*/tools/vim132
## install_append content
install -p -D -m 0644 vimrc %{buildroot}/usr/share/vim/

install ./vim-minimal %{buildroot}/usr/bin/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ex
/usr/bin/rview
/usr/bin/rvim
/usr/bin/view
/usr/bin/vim
/usr/bin/vimdiff
/usr/bin/vimtutor
/usr/bin/xxd
/usr/share/clear/optimized-elf/bin*

%files data
%defattr(-,root,root,-)
/usr/share/vim/vim82/autoload/README.txt
/usr/share/vim/vim82/autoload/RstFold.vim
/usr/share/vim/vim82/autoload/ada.vim
/usr/share/vim/vim82/autoload/adacomplete.vim
/usr/share/vim/vim82/autoload/ccomplete.vim
/usr/share/vim/vim82/autoload/clojurecomplete.vim
/usr/share/vim/vim82/autoload/context.vim
/usr/share/vim/vim82/autoload/contextcomplete.vim
/usr/share/vim/vim82/autoload/csscomplete.vim
/usr/share/vim/vim82/autoload/decada.vim
/usr/share/vim/vim82/autoload/dist/ft.vim
/usr/share/vim/vim82/autoload/getscript.vim
/usr/share/vim/vim82/autoload/gnat.vim
/usr/share/vim/vim82/autoload/gzip.vim
/usr/share/vim/vim82/autoload/haskellcomplete.vim
/usr/share/vim/vim82/autoload/htmlcomplete.vim
/usr/share/vim/vim82/autoload/javascriptcomplete.vim
/usr/share/vim/vim82/autoload/netrw.vim
/usr/share/vim/vim82/autoload/netrwFileHandlers.vim
/usr/share/vim/vim82/autoload/netrwSettings.vim
/usr/share/vim/vim82/autoload/netrw_gitignore.vim
/usr/share/vim/vim82/autoload/paste.vim
/usr/share/vim/vim82/autoload/phpcomplete.vim
/usr/share/vim/vim82/autoload/python3complete.vim
/usr/share/vim/vim82/autoload/pythoncomplete.vim
/usr/share/vim/vim82/autoload/rubycomplete.vim
/usr/share/vim/vim82/autoload/rust.vim
/usr/share/vim/vim82/autoload/rustfmt.vim
/usr/share/vim/vim82/autoload/spellfile.vim
/usr/share/vim/vim82/autoload/sqlcomplete.vim
/usr/share/vim/vim82/autoload/syntaxcomplete.vim
/usr/share/vim/vim82/autoload/tar.vim
/usr/share/vim/vim82/autoload/tohtml.vim
/usr/share/vim/vim82/autoload/vimball.vim
/usr/share/vim/vim82/autoload/xml/html32.vim
/usr/share/vim/vim82/autoload/xml/html401f.vim
/usr/share/vim/vim82/autoload/xml/html401s.vim
/usr/share/vim/vim82/autoload/xml/html401t.vim
/usr/share/vim/vim82/autoload/xml/html40f.vim
/usr/share/vim/vim82/autoload/xml/html40s.vim
/usr/share/vim/vim82/autoload/xml/html40t.vim
/usr/share/vim/vim82/autoload/xml/xhtml10f.vim
/usr/share/vim/vim82/autoload/xml/xhtml10s.vim
/usr/share/vim/vim82/autoload/xml/xhtml10t.vim
/usr/share/vim/vim82/autoload/xml/xhtml11.vim
/usr/share/vim/vim82/autoload/xml/xsd.vim
/usr/share/vim/vim82/autoload/xml/xsl.vim
/usr/share/vim/vim82/autoload/xmlcomplete.vim
/usr/share/vim/vim82/autoload/xmlformat.vim
/usr/share/vim/vim82/autoload/zip.vim
/usr/share/vim/vim82/bugreport.vim
/usr/share/vim/vim82/colors/README.txt
/usr/share/vim/vim82/colors/blue.vim
/usr/share/vim/vim82/colors/darkblue.vim
/usr/share/vim/vim82/colors/default.vim
/usr/share/vim/vim82/colors/delek.vim
/usr/share/vim/vim82/colors/desert.vim
/usr/share/vim/vim82/colors/elflord.vim
/usr/share/vim/vim82/colors/evening.vim
/usr/share/vim/vim82/colors/industry.vim
/usr/share/vim/vim82/colors/koehler.vim
/usr/share/vim/vim82/colors/lists/csscolors.vim
/usr/share/vim/vim82/colors/lists/default.vim
/usr/share/vim/vim82/colors/morning.vim
/usr/share/vim/vim82/colors/murphy.vim
/usr/share/vim/vim82/colors/pablo.vim
/usr/share/vim/vim82/colors/peachpuff.vim
/usr/share/vim/vim82/colors/ron.vim
/usr/share/vim/vim82/colors/shine.vim
/usr/share/vim/vim82/colors/slate.vim
/usr/share/vim/vim82/colors/tools/check_colors.vim
/usr/share/vim/vim82/colors/torte.vim
/usr/share/vim/vim82/colors/zellner.vim
/usr/share/vim/vim82/compiler/README.txt
/usr/share/vim/vim82/compiler/ant.vim
/usr/share/vim/vim82/compiler/bcc.vim
/usr/share/vim/vim82/compiler/bdf.vim
/usr/share/vim/vim82/compiler/cargo.vim
/usr/share/vim/vim82/compiler/checkstyle.vim
/usr/share/vim/vim82/compiler/cm3.vim
/usr/share/vim/vim82/compiler/context.vim
/usr/share/vim/vim82/compiler/cs.vim
/usr/share/vim/vim82/compiler/csslint.vim
/usr/share/vim/vim82/compiler/cucumber.vim
/usr/share/vim/vim82/compiler/dart.vim
/usr/share/vim/vim82/compiler/dart2js.vim
/usr/share/vim/vim82/compiler/dart2native.vim
/usr/share/vim/vim82/compiler/dartanalyser.vim
/usr/share/vim/vim82/compiler/dartdevc.vim
/usr/share/vim/vim82/compiler/dartdoc.vim
/usr/share/vim/vim82/compiler/dartfmt.vim
/usr/share/vim/vim82/compiler/decada.vim
/usr/share/vim/vim82/compiler/dot.vim
/usr/share/vim/vim82/compiler/erlang.vim
/usr/share/vim/vim82/compiler/eruby.vim
/usr/share/vim/vim82/compiler/eslint.vim
/usr/share/vim/vim82/compiler/fbc.vim
/usr/share/vim/vim82/compiler/fortran_F.vim
/usr/share/vim/vim82/compiler/fortran_cv.vim
/usr/share/vim/vim82/compiler/fortran_elf90.vim
/usr/share/vim/vim82/compiler/fortran_g77.vim
/usr/share/vim/vim82/compiler/fortran_lf95.vim
/usr/share/vim/vim82/compiler/fpc.vim
/usr/share/vim/vim82/compiler/g95.vim
/usr/share/vim/vim82/compiler/gawk.vim
/usr/share/vim/vim82/compiler/gcc.vim
/usr/share/vim/vim82/compiler/gfortran.vim
/usr/share/vim/vim82/compiler/ghc.vim
/usr/share/vim/vim82/compiler/gjs.vim
/usr/share/vim/vim82/compiler/gnat.vim
/usr/share/vim/vim82/compiler/haml.vim
/usr/share/vim/vim82/compiler/hp_acc.vim
/usr/share/vim/vim82/compiler/icc.vim
/usr/share/vim/vim82/compiler/ifort.vim
/usr/share/vim/vim82/compiler/intel.vim
/usr/share/vim/vim82/compiler/irix5_c.vim
/usr/share/vim/vim82/compiler/irix5_cpp.vim
/usr/share/vim/vim82/compiler/javac.vim
/usr/share/vim/vim82/compiler/jest.vim
/usr/share/vim/vim82/compiler/jikes.vim
/usr/share/vim/vim82/compiler/jjs.vim
/usr/share/vim/vim82/compiler/jshint.vim
/usr/share/vim/vim82/compiler/jsonlint.vim
/usr/share/vim/vim82/compiler/mcs.vim
/usr/share/vim/vim82/compiler/mips_c.vim
/usr/share/vim/vim82/compiler/mipspro_c89.vim
/usr/share/vim/vim82/compiler/mipspro_cpp.vim
/usr/share/vim/vim82/compiler/modelsim_vcom.vim
/usr/share/vim/vim82/compiler/msbuild.vim
/usr/share/vim/vim82/compiler/msvc.vim
/usr/share/vim/vim82/compiler/neato.vim
/usr/share/vim/vim82/compiler/ocaml.vim
/usr/share/vim/vim82/compiler/onsgmls.vim
/usr/share/vim/vim82/compiler/pbx.vim
/usr/share/vim/vim82/compiler/perl.vim
/usr/share/vim/vim82/compiler/php.vim
/usr/share/vim/vim82/compiler/powershell.vim
/usr/share/vim/vim82/compiler/pylint.vim
/usr/share/vim/vim82/compiler/pyunit.vim
/usr/share/vim/vim82/compiler/rake.vim
/usr/share/vim/vim82/compiler/rhino.vim
/usr/share/vim/vim82/compiler/rspec.vim
/usr/share/vim/vim82/compiler/rst.vim
/usr/share/vim/vim82/compiler/rubocop.vim
/usr/share/vim/vim82/compiler/ruby.vim
/usr/share/vim/vim82/compiler/rubyunit.vim
/usr/share/vim/vim82/compiler/rustc.vim
/usr/share/vim/vim82/compiler/sass.vim
/usr/share/vim/vim82/compiler/scdoc.vim
/usr/share/vim/vim82/compiler/se.vim
/usr/share/vim/vim82/compiler/shellcheck.vim
/usr/share/vim/vim82/compiler/sml.vim
/usr/share/vim/vim82/compiler/spectral.vim
/usr/share/vim/vim82/compiler/splint.vim
/usr/share/vim/vim82/compiler/stack.vim
/usr/share/vim/vim82/compiler/standard.vim
/usr/share/vim/vim82/compiler/stylelint.vim
/usr/share/vim/vim82/compiler/tcl.vim
/usr/share/vim/vim82/compiler/tex.vim
/usr/share/vim/vim82/compiler/tidy.vim
/usr/share/vim/vim82/compiler/ts-node.vim
/usr/share/vim/vim82/compiler/tsc.vim
/usr/share/vim/vim82/compiler/typedoc.vim
/usr/share/vim/vim82/compiler/xbuild.vim
/usr/share/vim/vim82/compiler/xmllint.vim
/usr/share/vim/vim82/compiler/xmlwf.vim
/usr/share/vim/vim82/compiler/xo.vim
/usr/share/vim/vim82/compiler/yamllint.vim
/usr/share/vim/vim82/compiler/zsh.vim
/usr/share/vim/vim82/defaults.vim
/usr/share/vim/vim82/delmenu.vim
/usr/share/vim/vim82/doc/arabic.txt
/usr/share/vim/vim82/doc/autocmd.txt
/usr/share/vim/vim82/doc/change.txt
/usr/share/vim/vim82/doc/channel.txt
/usr/share/vim/vim82/doc/cmdline.txt
/usr/share/vim/vim82/doc/debug.txt
/usr/share/vim/vim82/doc/debugger.txt
/usr/share/vim/vim82/doc/develop.txt
/usr/share/vim/vim82/doc/diff.txt
/usr/share/vim/vim82/doc/digraph.txt
/usr/share/vim/vim82/doc/editing.txt
/usr/share/vim/vim82/doc/eval.txt
/usr/share/vim/vim82/doc/farsi.txt
/usr/share/vim/vim82/doc/filetype.txt
/usr/share/vim/vim82/doc/fold.txt
/usr/share/vim/vim82/doc/ft_ada.txt
/usr/share/vim/vim82/doc/ft_ps1.txt
/usr/share/vim/vim82/doc/ft_raku.txt
/usr/share/vim/vim82/doc/ft_rust.txt
/usr/share/vim/vim82/doc/ft_sql.txt
/usr/share/vim/vim82/doc/gui.txt
/usr/share/vim/vim82/doc/gui_w32.txt
/usr/share/vim/vim82/doc/gui_x11.txt
/usr/share/vim/vim82/doc/hangulin.txt
/usr/share/vim/vim82/doc/hebrew.txt
/usr/share/vim/vim82/doc/help.txt
/usr/share/vim/vim82/doc/helphelp.txt
/usr/share/vim/vim82/doc/howto.txt
/usr/share/vim/vim82/doc/if_cscop.txt
/usr/share/vim/vim82/doc/if_lua.txt
/usr/share/vim/vim82/doc/if_mzsch.txt
/usr/share/vim/vim82/doc/if_ole.txt
/usr/share/vim/vim82/doc/if_perl.txt
/usr/share/vim/vim82/doc/if_pyth.txt
/usr/share/vim/vim82/doc/if_ruby.txt
/usr/share/vim/vim82/doc/if_sniff.txt
/usr/share/vim/vim82/doc/if_tcl.txt
/usr/share/vim/vim82/doc/indent.txt
/usr/share/vim/vim82/doc/index.txt
/usr/share/vim/vim82/doc/insert.txt
/usr/share/vim/vim82/doc/intro.txt
/usr/share/vim/vim82/doc/map.txt
/usr/share/vim/vim82/doc/mbyte.txt
/usr/share/vim/vim82/doc/message.txt
/usr/share/vim/vim82/doc/mlang.txt
/usr/share/vim/vim82/doc/motion.txt
/usr/share/vim/vim82/doc/netbeans.txt
/usr/share/vim/vim82/doc/options.txt
/usr/share/vim/vim82/doc/os_390.txt
/usr/share/vim/vim82/doc/os_amiga.txt
/usr/share/vim/vim82/doc/os_beos.txt
/usr/share/vim/vim82/doc/os_dos.txt
/usr/share/vim/vim82/doc/os_haiku.txt
/usr/share/vim/vim82/doc/os_mac.txt
/usr/share/vim/vim82/doc/os_mint.txt
/usr/share/vim/vim82/doc/os_msdos.txt
/usr/share/vim/vim82/doc/os_os2.txt
/usr/share/vim/vim82/doc/os_qnx.txt
/usr/share/vim/vim82/doc/os_risc.txt
/usr/share/vim/vim82/doc/os_unix.txt
/usr/share/vim/vim82/doc/os_vms.txt
/usr/share/vim/vim82/doc/os_win32.txt
/usr/share/vim/vim82/doc/pattern.txt
/usr/share/vim/vim82/doc/pi_getscript.txt
/usr/share/vim/vim82/doc/pi_gzip.txt
/usr/share/vim/vim82/doc/pi_logipat.txt
/usr/share/vim/vim82/doc/pi_netrw.txt
/usr/share/vim/vim82/doc/pi_paren.txt
/usr/share/vim/vim82/doc/pi_spec.txt
/usr/share/vim/vim82/doc/pi_tar.txt
/usr/share/vim/vim82/doc/pi_vimball.txt
/usr/share/vim/vim82/doc/pi_zip.txt
/usr/share/vim/vim82/doc/popup.txt
/usr/share/vim/vim82/doc/print.txt
/usr/share/vim/vim82/doc/quickfix.txt
/usr/share/vim/vim82/doc/quickref.txt
/usr/share/vim/vim82/doc/quotes.txt
/usr/share/vim/vim82/doc/recover.txt
/usr/share/vim/vim82/doc/remote.txt
/usr/share/vim/vim82/doc/repeat.txt
/usr/share/vim/vim82/doc/rileft.txt
/usr/share/vim/vim82/doc/russian.txt
/usr/share/vim/vim82/doc/scroll.txt
/usr/share/vim/vim82/doc/sign.txt
/usr/share/vim/vim82/doc/spell.txt
/usr/share/vim/vim82/doc/sponsor.txt
/usr/share/vim/vim82/doc/starting.txt
/usr/share/vim/vim82/doc/syntax.txt
/usr/share/vim/vim82/doc/tabpage.txt
/usr/share/vim/vim82/doc/tags
/usr/share/vim/vim82/doc/tagsrch.txt
/usr/share/vim/vim82/doc/term.txt
/usr/share/vim/vim82/doc/terminal.txt
/usr/share/vim/vim82/doc/testing.txt
/usr/share/vim/vim82/doc/textprop.txt
/usr/share/vim/vim82/doc/tips.txt
/usr/share/vim/vim82/doc/todo.txt
/usr/share/vim/vim82/doc/uganda.txt
/usr/share/vim/vim82/doc/undo.txt
/usr/share/vim/vim82/doc/usr_01.txt
/usr/share/vim/vim82/doc/usr_02.txt
/usr/share/vim/vim82/doc/usr_03.txt
/usr/share/vim/vim82/doc/usr_04.txt
/usr/share/vim/vim82/doc/usr_05.txt
/usr/share/vim/vim82/doc/usr_06.txt
/usr/share/vim/vim82/doc/usr_07.txt
/usr/share/vim/vim82/doc/usr_08.txt
/usr/share/vim/vim82/doc/usr_09.txt
/usr/share/vim/vim82/doc/usr_10.txt
/usr/share/vim/vim82/doc/usr_11.txt
/usr/share/vim/vim82/doc/usr_12.txt
/usr/share/vim/vim82/doc/usr_20.txt
/usr/share/vim/vim82/doc/usr_21.txt
/usr/share/vim/vim82/doc/usr_22.txt
/usr/share/vim/vim82/doc/usr_23.txt
/usr/share/vim/vim82/doc/usr_24.txt
/usr/share/vim/vim82/doc/usr_25.txt
/usr/share/vim/vim82/doc/usr_26.txt
/usr/share/vim/vim82/doc/usr_27.txt
/usr/share/vim/vim82/doc/usr_28.txt
/usr/share/vim/vim82/doc/usr_29.txt
/usr/share/vim/vim82/doc/usr_30.txt
/usr/share/vim/vim82/doc/usr_31.txt
/usr/share/vim/vim82/doc/usr_32.txt
/usr/share/vim/vim82/doc/usr_40.txt
/usr/share/vim/vim82/doc/usr_41.txt
/usr/share/vim/vim82/doc/usr_42.txt
/usr/share/vim/vim82/doc/usr_43.txt
/usr/share/vim/vim82/doc/usr_44.txt
/usr/share/vim/vim82/doc/usr_45.txt
/usr/share/vim/vim82/doc/usr_46.txt
/usr/share/vim/vim82/doc/usr_90.txt
/usr/share/vim/vim82/doc/usr_toc.txt
/usr/share/vim/vim82/doc/various.txt
/usr/share/vim/vim82/doc/version4.txt
/usr/share/vim/vim82/doc/version5.txt
/usr/share/vim/vim82/doc/version6.txt
/usr/share/vim/vim82/doc/version7.txt
/usr/share/vim/vim82/doc/version8.txt
/usr/share/vim/vim82/doc/vi_diff.txt
/usr/share/vim/vim82/doc/vim2html.pl
/usr/share/vim/vim82/doc/vim9.txt
/usr/share/vim/vim82/doc/visual.txt
/usr/share/vim/vim82/doc/windows.txt
/usr/share/vim/vim82/doc/workshop.txt
/usr/share/vim/vim82/evim.vim
/usr/share/vim/vim82/filetype.vim
/usr/share/vim/vim82/ftoff.vim
/usr/share/vim/vim82/ftplugin.vim
/usr/share/vim/vim82/ftplugin/8th.vim
/usr/share/vim/vim82/ftplugin/README.txt
/usr/share/vim/vim82/ftplugin/a2ps.vim
/usr/share/vim/vim82/ftplugin/aap.vim
/usr/share/vim/vim82/ftplugin/abap.vim
/usr/share/vim/vim82/ftplugin/abaqus.vim
/usr/share/vim/vim82/ftplugin/ada.vim
/usr/share/vim/vim82/ftplugin/alsaconf.vim
/usr/share/vim/vim82/ftplugin/ant.vim
/usr/share/vim/vim82/ftplugin/arch.vim
/usr/share/vim/vim82/ftplugin/art.vim
/usr/share/vim/vim82/ftplugin/aspvbs.vim
/usr/share/vim/vim82/ftplugin/automake.vim
/usr/share/vim/vim82/ftplugin/awk.vim
/usr/share/vim/vim82/ftplugin/bash.vim
/usr/share/vim/vim82/ftplugin/basic.vim
/usr/share/vim/vim82/ftplugin/bdf.vim
/usr/share/vim/vim82/ftplugin/bst.vim
/usr/share/vim/vim82/ftplugin/btm.vim
/usr/share/vim/vim82/ftplugin/bzl.vim
/usr/share/vim/vim82/ftplugin/c.vim
/usr/share/vim/vim82/ftplugin/calendar.vim
/usr/share/vim/vim82/ftplugin/cdrdaoconf.vim
/usr/share/vim/vim82/ftplugin/cfg.vim
/usr/share/vim/vim82/ftplugin/ch.vim
/usr/share/vim/vim82/ftplugin/changelog.vim
/usr/share/vim/vim82/ftplugin/chicken.vim
/usr/share/vim/vim82/ftplugin/clojure.vim
/usr/share/vim/vim82/ftplugin/cmake.vim
/usr/share/vim/vim82/ftplugin/cobol.vim
/usr/share/vim/vim82/ftplugin/conf.vim
/usr/share/vim/vim82/ftplugin/config.vim
/usr/share/vim/vim82/ftplugin/context.vim
/usr/share/vim/vim82/ftplugin/cpp.vim
/usr/share/vim/vim82/ftplugin/crm.vim
/usr/share/vim/vim82/ftplugin/cs.vim
/usr/share/vim/vim82/ftplugin/csc.vim
/usr/share/vim/vim82/ftplugin/csh.vim
/usr/share/vim/vim82/ftplugin/css.vim
/usr/share/vim/vim82/ftplugin/cucumber.vim
/usr/share/vim/vim82/ftplugin/cvsrc.vim
/usr/share/vim/vim82/ftplugin/debchangelog.vim
/usr/share/vim/vim82/ftplugin/debcontrol.vim
/usr/share/vim/vim82/ftplugin/denyhosts.vim
/usr/share/vim/vim82/ftplugin/dictconf.vim
/usr/share/vim/vim82/ftplugin/dictdconf.vim
/usr/share/vim/vim82/ftplugin/diff.vim
/usr/share/vim/vim82/ftplugin/dircolors.vim
/usr/share/vim/vim82/ftplugin/docbk.vim
/usr/share/vim/vim82/ftplugin/dockerfile.vim
/usr/share/vim/vim82/ftplugin/dosbatch.vim
/usr/share/vim/vim82/ftplugin/dosini.vim
/usr/share/vim/vim82/ftplugin/dtd.vim
/usr/share/vim/vim82/ftplugin/dtrace.vim
/usr/share/vim/vim82/ftplugin/dune.vim
/usr/share/vim/vim82/ftplugin/eiffel.vim
/usr/share/vim/vim82/ftplugin/elinks.vim
/usr/share/vim/vim82/ftplugin/elm.vim
/usr/share/vim/vim82/ftplugin/erlang.vim
/usr/share/vim/vim82/ftplugin/eruby.vim
/usr/share/vim/vim82/ftplugin/eterm.vim
/usr/share/vim/vim82/ftplugin/falcon.vim
/usr/share/vim/vim82/ftplugin/fetchmail.vim
/usr/share/vim/vim82/ftplugin/flexwiki.vim
/usr/share/vim/vim82/ftplugin/fortran.vim
/usr/share/vim/vim82/ftplugin/fpcmake.vim
/usr/share/vim/vim82/ftplugin/framescript.vim
/usr/share/vim/vim82/ftplugin/freebasic.vim
/usr/share/vim/vim82/ftplugin/fstab.vim
/usr/share/vim/vim82/ftplugin/fvwm.vim
/usr/share/vim/vim82/ftplugin/gdb.vim
/usr/share/vim/vim82/ftplugin/git.vim
/usr/share/vim/vim82/ftplugin/gitcommit.vim
/usr/share/vim/vim82/ftplugin/gitconfig.vim
/usr/share/vim/vim82/ftplugin/gitrebase.vim
/usr/share/vim/vim82/ftplugin/gitsendemail.vim
/usr/share/vim/vim82/ftplugin/gpg.vim
/usr/share/vim/vim82/ftplugin/gprof.vim
/usr/share/vim/vim82/ftplugin/groovy.vim
/usr/share/vim/vim82/ftplugin/group.vim
/usr/share/vim/vim82/ftplugin/grub.vim
/usr/share/vim/vim82/ftplugin/haml.vim
/usr/share/vim/vim82/ftplugin/hamster.vim
/usr/share/vim/vim82/ftplugin/haskell.vim
/usr/share/vim/vim82/ftplugin/help.vim
/usr/share/vim/vim82/ftplugin/hgcommit.vim
/usr/share/vim/vim82/ftplugin/hog.vim
/usr/share/vim/vim82/ftplugin/hostconf.vim
/usr/share/vim/vim82/ftplugin/hostsaccess.vim
/usr/share/vim/vim82/ftplugin/html.vim
/usr/share/vim/vim82/ftplugin/htmldjango.vim
/usr/share/vim/vim82/ftplugin/indent.vim
/usr/share/vim/vim82/ftplugin/initex.vim
/usr/share/vim/vim82/ftplugin/ishd.vim
/usr/share/vim/vim82/ftplugin/j.vim
/usr/share/vim/vim82/ftplugin/java.vim
/usr/share/vim/vim82/ftplugin/javascript.vim
/usr/share/vim/vim82/ftplugin/javascriptreact.vim
/usr/share/vim/vim82/ftplugin/jproperties.vim
/usr/share/vim/vim82/ftplugin/json.vim
/usr/share/vim/vim82/ftplugin/jsonc.vim
/usr/share/vim/vim82/ftplugin/jsp.vim
/usr/share/vim/vim82/ftplugin/julia.vim
/usr/share/vim/vim82/ftplugin/kconfig.vim
/usr/share/vim/vim82/ftplugin/kwt.vim
/usr/share/vim/vim82/ftplugin/ld.vim
/usr/share/vim/vim82/ftplugin/less.vim
/usr/share/vim/vim82/ftplugin/lftp.vim
/usr/share/vim/vim82/ftplugin/libao.vim
/usr/share/vim/vim82/ftplugin/limits.vim
/usr/share/vim/vim82/ftplugin/liquid.vim
/usr/share/vim/vim82/ftplugin/lisp.vim
/usr/share/vim/vim82/ftplugin/logcheck.vim
/usr/share/vim/vim82/ftplugin/loginaccess.vim
/usr/share/vim/vim82/ftplugin/logindefs.vim
/usr/share/vim/vim82/ftplugin/logtalk.dict
/usr/share/vim/vim82/ftplugin/logtalk.vim
/usr/share/vim/vim82/ftplugin/lprolog.vim
/usr/share/vim/vim82/ftplugin/lua.vim
/usr/share/vim/vim82/ftplugin/m3build.vim
/usr/share/vim/vim82/ftplugin/m3quake.vim
/usr/share/vim/vim82/ftplugin/m4.vim
/usr/share/vim/vim82/ftplugin/mail.vim
/usr/share/vim/vim82/ftplugin/mailaliases.vim
/usr/share/vim/vim82/ftplugin/mailcap.vim
/usr/share/vim/vim82/ftplugin/make.vim
/usr/share/vim/vim82/ftplugin/man.vim
/usr/share/vim/vim82/ftplugin/manconf.vim
/usr/share/vim/vim82/ftplugin/markdown.vim
/usr/share/vim/vim82/ftplugin/masm.vim
/usr/share/vim/vim82/ftplugin/matlab.vim
/usr/share/vim/vim82/ftplugin/mf.vim
/usr/share/vim/vim82/ftplugin/mma.vim
/usr/share/vim/vim82/ftplugin/modconf.vim
/usr/share/vim/vim82/ftplugin/modula2.vim
/usr/share/vim/vim82/ftplugin/modula3.vim
/usr/share/vim/vim82/ftplugin/mp.vim
/usr/share/vim/vim82/ftplugin/mplayerconf.vim
/usr/share/vim/vim82/ftplugin/mrxvtrc.vim
/usr/share/vim/vim82/ftplugin/msmessages.vim
/usr/share/vim/vim82/ftplugin/muttrc.vim
/usr/share/vim/vim82/ftplugin/nanorc.vim
/usr/share/vim/vim82/ftplugin/neomuttrc.vim
/usr/share/vim/vim82/ftplugin/netrc.vim
/usr/share/vim/vim82/ftplugin/nginx.vim
/usr/share/vim/vim82/ftplugin/nroff.vim
/usr/share/vim/vim82/ftplugin/nsis.vim
/usr/share/vim/vim82/ftplugin/objc.vim
/usr/share/vim/vim82/ftplugin/ocaml.vim
/usr/share/vim/vim82/ftplugin/occam.vim
/usr/share/vim/vim82/ftplugin/octave.vim
/usr/share/vim/vim82/ftplugin/pamconf.vim
/usr/share/vim/vim82/ftplugin/pascal.vim
/usr/share/vim/vim82/ftplugin/passwd.vim
/usr/share/vim/vim82/ftplugin/pbtxt.vim
/usr/share/vim/vim82/ftplugin/pdf.vim
/usr/share/vim/vim82/ftplugin/perl.vim
/usr/share/vim/vim82/ftplugin/php.vim
/usr/share/vim/vim82/ftplugin/pinfo.vim
/usr/share/vim/vim82/ftplugin/plaintex.vim
/usr/share/vim/vim82/ftplugin/poke.vim
/usr/share/vim/vim82/ftplugin/postscr.vim
/usr/share/vim/vim82/ftplugin/procmail.vim
/usr/share/vim/vim82/ftplugin/prolog.vim
/usr/share/vim/vim82/ftplugin/protocols.vim
/usr/share/vim/vim82/ftplugin/ps1.vim
/usr/share/vim/vim82/ftplugin/ps1xml.vim
/usr/share/vim/vim82/ftplugin/pyrex.vim
/usr/share/vim/vim82/ftplugin/python.vim
/usr/share/vim/vim82/ftplugin/qf.vim
/usr/share/vim/vim82/ftplugin/quake.vim
/usr/share/vim/vim82/ftplugin/r.vim
/usr/share/vim/vim82/ftplugin/racc.vim
/usr/share/vim/vim82/ftplugin/raku.vim
/usr/share/vim/vim82/ftplugin/readline.vim
/usr/share/vim/vim82/ftplugin/registry.vim
/usr/share/vim/vim82/ftplugin/reva.vim
/usr/share/vim/vim82/ftplugin/rhelp.vim
/usr/share/vim/vim82/ftplugin/rmd.vim
/usr/share/vim/vim82/ftplugin/rnc.vim
/usr/share/vim/vim82/ftplugin/rnoweb.vim
/usr/share/vim/vim82/ftplugin/rpl.vim
/usr/share/vim/vim82/ftplugin/rrst.vim
/usr/share/vim/vim82/ftplugin/rst.vim
/usr/share/vim/vim82/ftplugin/ruby.vim
/usr/share/vim/vim82/ftplugin/rust.vim
/usr/share/vim/vim82/ftplugin/sass.vim
/usr/share/vim/vim82/ftplugin/sbt.vim
/usr/share/vim/vim82/ftplugin/scala.vim
/usr/share/vim/vim82/ftplugin/scdoc.vim
/usr/share/vim/vim82/ftplugin/scheme.vim
/usr/share/vim/vim82/ftplugin/screen.vim
/usr/share/vim/vim82/ftplugin/scss.vim
/usr/share/vim/vim82/ftplugin/sensors.vim
/usr/share/vim/vim82/ftplugin/services.vim
/usr/share/vim/vim82/ftplugin/setserial.vim
/usr/share/vim/vim82/ftplugin/sexplib.vim
/usr/share/vim/vim82/ftplugin/sgml.vim
/usr/share/vim/vim82/ftplugin/sh.vim
/usr/share/vim/vim82/ftplugin/sieve.vim
/usr/share/vim/vim82/ftplugin/slpconf.vim
/usr/share/vim/vim82/ftplugin/slpreg.vim
/usr/share/vim/vim82/ftplugin/slpspi.vim
/usr/share/vim/vim82/ftplugin/spec.vim
/usr/share/vim/vim82/ftplugin/sql.vim
/usr/share/vim/vim82/ftplugin/sshconfig.vim
/usr/share/vim/vim82/ftplugin/sudoers.vim
/usr/share/vim/vim82/ftplugin/svg.vim
/usr/share/vim/vim82/ftplugin/swift.vim
/usr/share/vim/vim82/ftplugin/swiftgyb.vim
/usr/share/vim/vim82/ftplugin/sysctl.vim
/usr/share/vim/vim82/ftplugin/systemd.vim
/usr/share/vim/vim82/ftplugin/systemverilog.vim
/usr/share/vim/vim82/ftplugin/tcl.vim
/usr/share/vim/vim82/ftplugin/tcsh.vim
/usr/share/vim/vim82/ftplugin/terminfo.vim
/usr/share/vim/vim82/ftplugin/tex.vim
/usr/share/vim/vim82/ftplugin/text.vim
/usr/share/vim/vim82/ftplugin/tidy.vim
/usr/share/vim/vim82/ftplugin/tmux.vim
/usr/share/vim/vim82/ftplugin/toml.vim
/usr/share/vim/vim82/ftplugin/treetop.vim
/usr/share/vim/vim82/ftplugin/tt2html.vim
/usr/share/vim/vim82/ftplugin/typescript.vim
/usr/share/vim/vim82/ftplugin/typescriptreact.vim
/usr/share/vim/vim82/ftplugin/udevconf.vim
/usr/share/vim/vim82/ftplugin/udevperm.vim
/usr/share/vim/vim82/ftplugin/udevrules.vim
/usr/share/vim/vim82/ftplugin/updatedb.vim
/usr/share/vim/vim82/ftplugin/vb.vim
/usr/share/vim/vim82/ftplugin/verilog.vim
/usr/share/vim/vim82/ftplugin/vhdl.vim
/usr/share/vim/vim82/ftplugin/vim.vim
/usr/share/vim/vim82/ftplugin/vroom.vim
/usr/share/vim/vim82/ftplugin/wast.vim
/usr/share/vim/vim82/ftplugin/xdefaults.vim
/usr/share/vim/vim82/ftplugin/xf86conf.vim
/usr/share/vim/vim82/ftplugin/xhtml.vim
/usr/share/vim/vim82/ftplugin/xinetd.vim
/usr/share/vim/vim82/ftplugin/xml.vim
/usr/share/vim/vim82/ftplugin/xmodmap.vim
/usr/share/vim/vim82/ftplugin/xs.vim
/usr/share/vim/vim82/ftplugin/xsd.vim
/usr/share/vim/vim82/ftplugin/xslt.vim
/usr/share/vim/vim82/ftplugin/yaml.vim
/usr/share/vim/vim82/ftplugin/zimbu.vim
/usr/share/vim/vim82/ftplugin/zsh.vim
/usr/share/vim/vim82/ftplugof.vim
/usr/share/vim/vim82/gvimrc_example.vim
/usr/share/vim/vim82/indent.vim
/usr/share/vim/vim82/indent/README.txt
/usr/share/vim/vim82/indent/aap.vim
/usr/share/vim/vim82/indent/ada.vim
/usr/share/vim/vim82/indent/ant.vim
/usr/share/vim/vim82/indent/automake.vim
/usr/share/vim/vim82/indent/awk.vim
/usr/share/vim/vim82/indent/bash.vim
/usr/share/vim/vim82/indent/bib.vim
/usr/share/vim/vim82/indent/bst.vim
/usr/share/vim/vim82/indent/bzl.vim
/usr/share/vim/vim82/indent/c.vim
/usr/share/vim/vim82/indent/cdl.vim
/usr/share/vim/vim82/indent/ch.vim
/usr/share/vim/vim82/indent/chaiscript.vim
/usr/share/vim/vim82/indent/changelog.vim
/usr/share/vim/vim82/indent/clojure.vim
/usr/share/vim/vim82/indent/cmake.vim
/usr/share/vim/vim82/indent/cobol.vim
/usr/share/vim/vim82/indent/config.vim
/usr/share/vim/vim82/indent/context.vim
/usr/share/vim/vim82/indent/cpp.vim
/usr/share/vim/vim82/indent/cs.vim
/usr/share/vim/vim82/indent/css.vim
/usr/share/vim/vim82/indent/cucumber.vim
/usr/share/vim/vim82/indent/cuda.vim
/usr/share/vim/vim82/indent/d.vim
/usr/share/vim/vim82/indent/dictconf.vim
/usr/share/vim/vim82/indent/dictdconf.vim
/usr/share/vim/vim82/indent/docbk.vim
/usr/share/vim/vim82/indent/dosbatch.vim
/usr/share/vim/vim82/indent/dtd.vim
/usr/share/vim/vim82/indent/dtrace.vim
/usr/share/vim/vim82/indent/dune.vim
/usr/share/vim/vim82/indent/dylan.vim
/usr/share/vim/vim82/indent/eiffel.vim
/usr/share/vim/vim82/indent/elm.vim
/usr/share/vim/vim82/indent/erlang.vim
/usr/share/vim/vim82/indent/eruby.vim
/usr/share/vim/vim82/indent/eterm.vim
/usr/share/vim/vim82/indent/falcon.vim
/usr/share/vim/vim82/indent/fortran.vim
/usr/share/vim/vim82/indent/framescript.vim
/usr/share/vim/vim82/indent/gitconfig.vim
/usr/share/vim/vim82/indent/gitolite.vim
/usr/share/vim/vim82/indent/haml.vim
/usr/share/vim/vim82/indent/hamster.vim
/usr/share/vim/vim82/indent/hog.vim
/usr/share/vim/vim82/indent/html.vim
/usr/share/vim/vim82/indent/htmldjango.vim
/usr/share/vim/vim82/indent/idlang.vim
/usr/share/vim/vim82/indent/ishd.vim
/usr/share/vim/vim82/indent/j.vim
/usr/share/vim/vim82/indent/java.vim
/usr/share/vim/vim82/indent/javascript.vim
/usr/share/vim/vim82/indent/javascriptreact.vim
/usr/share/vim/vim82/indent/json.vim
/usr/share/vim/vim82/indent/jsonc.vim
/usr/share/vim/vim82/indent/jsp.vim
/usr/share/vim/vim82/indent/julia.vim
/usr/share/vim/vim82/indent/ld.vim
/usr/share/vim/vim82/indent/less.vim
/usr/share/vim/vim82/indent/lifelines.vim
/usr/share/vim/vim82/indent/liquid.vim
/usr/share/vim/vim82/indent/lisp.vim
/usr/share/vim/vim82/indent/logtalk.vim
/usr/share/vim/vim82/indent/lua.vim
/usr/share/vim/vim82/indent/mail.vim
/usr/share/vim/vim82/indent/make.vim
/usr/share/vim/vim82/indent/matlab.vim
/usr/share/vim/vim82/indent/mf.vim
/usr/share/vim/vim82/indent/mma.vim
/usr/share/vim/vim82/indent/mp.vim
/usr/share/vim/vim82/indent/nginx.vim
/usr/share/vim/vim82/indent/nsis.vim
/usr/share/vim/vim82/indent/objc.vim
/usr/share/vim/vim82/indent/ocaml.vim
/usr/share/vim/vim82/indent/occam.vim
/usr/share/vim/vim82/indent/pascal.vim
/usr/share/vim/vim82/indent/perl.vim
/usr/share/vim/vim82/indent/php.vim
/usr/share/vim/vim82/indent/postscr.vim
/usr/share/vim/vim82/indent/pov.vim
/usr/share/vim/vim82/indent/prolog.vim
/usr/share/vim/vim82/indent/ps1.vim
/usr/share/vim/vim82/indent/pyrex.vim
/usr/share/vim/vim82/indent/python.vim
/usr/share/vim/vim82/indent/r.vim
/usr/share/vim/vim82/indent/raku.vim
/usr/share/vim/vim82/indent/raml.vim
/usr/share/vim/vim82/indent/readline.vim
/usr/share/vim/vim82/indent/rhelp.vim
/usr/share/vim/vim82/indent/rmd.vim
/usr/share/vim/vim82/indent/rnoweb.vim
/usr/share/vim/vim82/indent/rpl.vim
/usr/share/vim/vim82/indent/rrst.vim
/usr/share/vim/vim82/indent/rst.vim
/usr/share/vim/vim82/indent/ruby.vim
/usr/share/vim/vim82/indent/rust.vim
/usr/share/vim/vim82/indent/sas.vim
/usr/share/vim/vim82/indent/sass.vim
/usr/share/vim/vim82/indent/scala.vim
/usr/share/vim/vim82/indent/scheme.vim
/usr/share/vim/vim82/indent/scss.vim
/usr/share/vim/vim82/indent/sdl.vim
/usr/share/vim/vim82/indent/sh.vim
/usr/share/vim/vim82/indent/sml.vim
/usr/share/vim/vim82/indent/sql.vim
/usr/share/vim/vim82/indent/sqlanywhere.vim
/usr/share/vim/vim82/indent/sshconfig.vim
/usr/share/vim/vim82/indent/systemd.vim
/usr/share/vim/vim82/indent/systemverilog.vim
/usr/share/vim/vim82/indent/tcl.vim
/usr/share/vim/vim82/indent/tcsh.vim
/usr/share/vim/vim82/indent/teraterm.vim
/usr/share/vim/vim82/indent/tex.vim
/usr/share/vim/vim82/indent/tf.vim
/usr/share/vim/vim82/indent/tilde.vim
/usr/share/vim/vim82/indent/treetop.vim
/usr/share/vim/vim82/indent/typescript.vim
/usr/share/vim/vim82/indent/vb.vim
/usr/share/vim/vim82/indent/verilog.vim
/usr/share/vim/vim82/indent/vhdl.vim
/usr/share/vim/vim82/indent/vim.vim
/usr/share/vim/vim82/indent/vroom.vim
/usr/share/vim/vim82/indent/wast.vim
/usr/share/vim/vim82/indent/xf86conf.vim
/usr/share/vim/vim82/indent/xhtml.vim
/usr/share/vim/vim82/indent/xinetd.vim
/usr/share/vim/vim82/indent/xml.vim
/usr/share/vim/vim82/indent/xsd.vim
/usr/share/vim/vim82/indent/xslt.vim
/usr/share/vim/vim82/indent/yacc.vim
/usr/share/vim/vim82/indent/yaml.vim
/usr/share/vim/vim82/indent/zimbu.vim
/usr/share/vim/vim82/indent/zsh.vim
/usr/share/vim/vim82/indoff.vim
/usr/share/vim/vim82/keymap/README.txt
/usr/share/vim/vim82/keymap/accents.vim
/usr/share/vim/vim82/keymap/arabic.vim
/usr/share/vim/vim82/keymap/arabic_utf-8.vim
/usr/share/vim/vim82/keymap/armenian-eastern_utf-8.vim
/usr/share/vim/vim82/keymap/armenian-western_utf-8.vim
/usr/share/vim/vim82/keymap/belarusian-jcuken.vim
/usr/share/vim/vim82/keymap/bulgarian-bds.vim
/usr/share/vim/vim82/keymap/bulgarian-phonetic.vim
/usr/share/vim/vim82/keymap/canfr-win.vim
/usr/share/vim/vim82/keymap/croatian.vim
/usr/share/vim/vim82/keymap/croatian_cp1250.vim
/usr/share/vim/vim82/keymap/croatian_iso-8859-2.vim
/usr/share/vim/vim82/keymap/croatian_utf-8.vim
/usr/share/vim/vim82/keymap/czech.vim
/usr/share/vim/vim82/keymap/czech_utf-8.vim
/usr/share/vim/vim82/keymap/dvorak.vim
/usr/share/vim/vim82/keymap/esperanto.vim
/usr/share/vim/vim82/keymap/esperanto_utf-8.vim
/usr/share/vim/vim82/keymap/french-azerty.vim
/usr/share/vim/vim82/keymap/german-qwertz.vim
/usr/share/vim/vim82/keymap/greek.vim
/usr/share/vim/vim82/keymap/greek_cp1253.vim
/usr/share/vim/vim82/keymap/greek_cp737.vim
/usr/share/vim/vim82/keymap/greek_iso-8859-7.vim
/usr/share/vim/vim82/keymap/greek_utf-8.vim
/usr/share/vim/vim82/keymap/hebrew.vim
/usr/share/vim/vim82/keymap/hebrew_cp1255.vim
/usr/share/vim/vim82/keymap/hebrew_iso-8859-8.vim
/usr/share/vim/vim82/keymap/hebrew_utf-8.vim
/usr/share/vim/vim82/keymap/hebrewp.vim
/usr/share/vim/vim82/keymap/hebrewp_cp1255.vim
/usr/share/vim/vim82/keymap/hebrewp_iso-8859-8.vim
/usr/share/vim/vim82/keymap/hebrewp_utf-8.vim
/usr/share/vim/vim82/keymap/kana.vim
/usr/share/vim/vim82/keymap/kazakh-jcuken.vim
/usr/share/vim/vim82/keymap/korean-dubeolsik_utf-8.vim
/usr/share/vim/vim82/keymap/korean.vim
/usr/share/vim/vim82/keymap/lithuanian-baltic.vim
/usr/share/vim/vim82/keymap/magyar_utf-8.vim
/usr/share/vim/vim82/keymap/mongolian_utf-8.vim
/usr/share/vim/vim82/keymap/oldturkic-orkhon_utf-8.vim
/usr/share/vim/vim82/keymap/oldturkic-yenisei_utf-8.vim
/usr/share/vim/vim82/keymap/persian-iranian_utf-8.vim
/usr/share/vim/vim82/keymap/persian.vim
/usr/share/vim/vim82/keymap/pinyin.vim
/usr/share/vim/vim82/keymap/polish-slash.vim
/usr/share/vim/vim82/keymap/polish-slash_cp1250.vim
/usr/share/vim/vim82/keymap/polish-slash_cp852.vim
/usr/share/vim/vim82/keymap/polish-slash_iso-8859-2.vim
/usr/share/vim/vim82/keymap/polish-slash_utf-8.vim
/usr/share/vim/vim82/keymap/russian-dvorak.vim
/usr/share/vim/vim82/keymap/russian-jcuken.vim
/usr/share/vim/vim82/keymap/russian-jcukenmac.vim
/usr/share/vim/vim82/keymap/russian-jcukenwin.vim
/usr/share/vim/vim82/keymap/russian-jcukenwintype.vim
/usr/share/vim/vim82/keymap/russian-typograph.vim
/usr/share/vim/vim82/keymap/russian-yawerty.vim
/usr/share/vim/vim82/keymap/serbian-latin.vim
/usr/share/vim/vim82/keymap/serbian-latin_utf-8.vim
/usr/share/vim/vim82/keymap/serbian.vim
/usr/share/vim/vim82/keymap/serbian_cp1250.vim
/usr/share/vim/vim82/keymap/serbian_cp1251.vim
/usr/share/vim/vim82/keymap/serbian_iso-8859-2.vim
/usr/share/vim/vim82/keymap/serbian_iso-8859-5.vim
/usr/share/vim/vim82/keymap/serbian_utf-8.vim
/usr/share/vim/vim82/keymap/sinhala-phonetic_utf-8.vim
/usr/share/vim/vim82/keymap/sinhala.vim
/usr/share/vim/vim82/keymap/slovak.vim
/usr/share/vim/vim82/keymap/slovak_cp1250.vim
/usr/share/vim/vim82/keymap/slovak_iso-8859-2.vim
/usr/share/vim/vim82/keymap/slovak_utf-8.vim
/usr/share/vim/vim82/keymap/tamil_tscii.vim
/usr/share/vim/vim82/keymap/thaana-phonetic_utf-8.vim
/usr/share/vim/vim82/keymap/thaana.vim
/usr/share/vim/vim82/keymap/turkish-f.vim
/usr/share/vim/vim82/keymap/turkish-q.vim
/usr/share/vim/vim82/keymap/ukrainian-dvorak.vim
/usr/share/vim/vim82/keymap/ukrainian-jcuken.vim
/usr/share/vim/vim82/keymap/vietnamese-telex_utf-8.vim
/usr/share/vim/vim82/keymap/vietnamese-viqr_utf-8.vim
/usr/share/vim/vim82/keymap/vietnamese-vni_utf-8.vim
/usr/share/vim/vim82/lang/README.txt
/usr/share/vim/vim82/lang/af/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ca/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/cs.cp1250/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/cs/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/da/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/de/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/en_GB/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/eo/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/es/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/fi/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/fr/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ga/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/it/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ja.euc-jp/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ja.sjis/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ja/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ko.UTF-8/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ko/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/lv/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/menu_af.latin1.vim
/usr/share/vim/vim82/lang/menu_af.utf-8.vim
/usr/share/vim/vim82/lang/menu_af_af.latin1.vim
/usr/share/vim/vim82/lang/menu_af_af.utf-8.vim
/usr/share/vim/vim82/lang/menu_ca.latin1.vim
/usr/share/vim/vim82/lang/menu_ca.utf-8.vim
/usr/share/vim/vim82/lang/menu_ca_es.latin1.vim
/usr/share/vim/vim82/lang/menu_ca_es.utf-8.vim
/usr/share/vim/vim82/lang/menu_chinese(gb)_gb.936.vim
/usr/share/vim/vim82/lang/menu_chinese(taiwan)_taiwan.950.vim
/usr/share/vim/vim82/lang/menu_chinese_gb.936.vim
/usr/share/vim/vim82/lang/menu_chinese_taiwan.950.vim
/usr/share/vim/vim82/lang/menu_cs.cp1250.vim
/usr/share/vim/vim82/lang/menu_cs.latin1.vim
/usr/share/vim/vim82/lang/menu_cs_cz.cp1250.vim
/usr/share/vim/vim82/lang/menu_cs_cz.iso_8859-2.vim
/usr/share/vim/vim82/lang/menu_cs_cz.latin1.vim
/usr/share/vim/vim82/lang/menu_cs_cz.utf-8.vim
/usr/share/vim/vim82/lang/menu_czech_czech_republic.1250.vim
/usr/share/vim/vim82/lang/menu_czech_czech_republic.1252.vim
/usr/share/vim/vim82/lang/menu_czech_czech_republic.ascii.vim
/usr/share/vim/vim82/lang/menu_da.latin1.vim
/usr/share/vim/vim82/lang/menu_da.utf-8.vim
/usr/share/vim/vim82/lang/menu_de.latin1.vim
/usr/share/vim/vim82/lang/menu_de.utf-8.vim
/usr/share/vim/vim82/lang/menu_de_de.latin1.vim
/usr/share/vim/vim82/lang/menu_de_de.utf-8.vim
/usr/share/vim/vim82/lang/menu_en_gb.latin1.vim
/usr/share/vim/vim82/lang/menu_en_gb.utf-8.vim
/usr/share/vim/vim82/lang/menu_english_united_kingdom.1252.vim
/usr/share/vim/vim82/lang/menu_english_united_kingdom.ascii.vim
/usr/share/vim/vim82/lang/menu_eo.utf-8.vim
/usr/share/vim/vim82/lang/menu_eo_eo.utf-8.vim
/usr/share/vim/vim82/lang/menu_eo_xx.utf-8.vim
/usr/share/vim/vim82/lang/menu_es.latin1.vim
/usr/share/vim/vim82/lang/menu_es.utf-8.vim
/usr/share/vim/vim82/lang/menu_es_es.latin1.vim
/usr/share/vim/vim82/lang/menu_es_es.utf-8.vim
/usr/share/vim/vim82/lang/menu_fi.latin1.vim
/usr/share/vim/vim82/lang/menu_fi.utf-8.vim
/usr/share/vim/vim82/lang/menu_fi_fi.latin1.vim
/usr/share/vim/vim82/lang/menu_fi_fi.utf-8.vim
/usr/share/vim/vim82/lang/menu_finnish_finland.1252.vim
/usr/share/vim/vim82/lang/menu_fr.latin1.vim
/usr/share/vim/vim82/lang/menu_fr.utf-8.vim
/usr/share/vim/vim82/lang/menu_fr_fr.latin1.vim
/usr/share/vim/vim82/lang/menu_fr_fr.utf-8.vim
/usr/share/vim/vim82/lang/menu_french_france.1252.vim
/usr/share/vim/vim82/lang/menu_german_germany.1252.vim
/usr/share/vim/vim82/lang/menu_hu.iso_8859-2.vim
/usr/share/vim/vim82/lang/menu_hu.utf-8.vim
/usr/share/vim/vim82/lang/menu_hu_hu.iso_8859-2.vim
/usr/share/vim/vim82/lang/menu_hu_hu.utf-8.vim
/usr/share/vim/vim82/lang/menu_is.latin1.vim
/usr/share/vim/vim82/lang/menu_is.utf-8.vim
/usr/share/vim/vim82/lang/menu_is_is.latin1.vim
/usr/share/vim/vim82/lang/menu_is_is.utf-8.vim
/usr/share/vim/vim82/lang/menu_it.latin1.vim
/usr/share/vim/vim82/lang/menu_it.utf-8.vim
/usr/share/vim/vim82/lang/menu_it_it.latin1.vim
/usr/share/vim/vim82/lang/menu_it_it.utf-8.vim
/usr/share/vim/vim82/lang/menu_italian_italy.1252.vim
/usr/share/vim/vim82/lang/menu_ja.cp932.vim
/usr/share/vim/vim82/lang/menu_ja.euc-jp.vim
/usr/share/vim/vim82/lang/menu_ja.eucjp.vim
/usr/share/vim/vim82/lang/menu_ja.ujis.vim
/usr/share/vim/vim82/lang/menu_ja.utf-8.vim
/usr/share/vim/vim82/lang/menu_ja_jp.cp932.vim
/usr/share/vim/vim82/lang/menu_ja_jp.euc-jp.vim
/usr/share/vim/vim82/lang/menu_ja_jp.eucjp.vim
/usr/share/vim/vim82/lang/menu_ja_jp.ujis.vim
/usr/share/vim/vim82/lang/menu_ja_jp.utf-8.vim
/usr/share/vim/vim82/lang/menu_japanese_japan.932.vim
/usr/share/vim/vim82/lang/menu_ko.utf-8.vim
/usr/share/vim/vim82/lang/menu_ko_kr.euckr.vim
/usr/share/vim/vim82/lang/menu_ko_kr.utf-8.vim
/usr/share/vim/vim82/lang/menu_ko_kr.vim
/usr/share/vim/vim82/lang/menu_nl.latin1.vim
/usr/share/vim/vim82/lang/menu_nl.utf-8.vim
/usr/share/vim/vim82/lang/menu_nl_nl.latin1.vim
/usr/share/vim/vim82/lang/menu_nl_nl.utf-8.vim
/usr/share/vim/vim82/lang/menu_no.latin1.vim
/usr/share/vim/vim82/lang/menu_no.utf-8.vim
/usr/share/vim/vim82/lang/menu_no_no.latin1.vim
/usr/share/vim/vim82/lang/menu_no_no.utf-8.vim
/usr/share/vim/vim82/lang/menu_pl.cp1250.vim
/usr/share/vim/vim82/lang/menu_pl_pl.cp1250.vim
/usr/share/vim/vim82/lang/menu_pl_pl.iso_8859-2.vim
/usr/share/vim/vim82/lang/menu_pl_pl.utf-8.vim
/usr/share/vim/vim82/lang/menu_polish_poland.1250.vim
/usr/share/vim/vim82/lang/menu_pt_br.latin1.vim
/usr/share/vim/vim82/lang/menu_pt_br.utf-8.vim
/usr/share/vim/vim82/lang/menu_pt_br.vim
/usr/share/vim/vim82/lang/menu_pt_pt.latin1.vim
/usr/share/vim/vim82/lang/menu_pt_pt.utf-8.vim
/usr/share/vim/vim82/lang/menu_pt_pt.vim
/usr/share/vim/vim82/lang/menu_ru.utf-8.vim
/usr/share/vim/vim82/lang/menu_ru_ru.koi8-r.vim
/usr/share/vim/vim82/lang/menu_ru_ru.utf-8.vim
/usr/share/vim/vim82/lang/menu_ru_ru.vim
/usr/share/vim/vim82/lang/menu_sk.cp1250.vim
/usr/share/vim/vim82/lang/menu_sk_sk.1250.vim
/usr/share/vim/vim82/lang/menu_sk_sk.cp1250.vim
/usr/share/vim/vim82/lang/menu_sk_sk.iso_8859-2.vim
/usr/share/vim/vim82/lang/menu_sk_sk.vim
/usr/share/vim/vim82/lang/menu_sl_si.cp1250.vim
/usr/share/vim/vim82/lang/menu_sl_si.latin2.vim
/usr/share/vim/vim82/lang/menu_sl_si.utf-8.vim
/usr/share/vim/vim82/lang/menu_slovak_slovak_republic.1250.vim
/usr/share/vim/vim82/lang/menu_spanish_spain.850.vim
/usr/share/vim/vim82/lang/menu_sr.utf-8.vim
/usr/share/vim/vim82/lang/menu_sr_rs.ascii.vim
/usr/share/vim/vim82/lang/menu_sr_rs.iso_8859-2.vim
/usr/share/vim/vim82/lang/menu_sr_rs.iso_8859-5.vim
/usr/share/vim/vim82/lang/menu_sr_rs.utf-8.vim
/usr/share/vim/vim82/lang/menu_sr_yu.ascii.vim
/usr/share/vim/vim82/lang/menu_sr_yu.iso_8859-2.vim
/usr/share/vim/vim82/lang/menu_sr_yu.iso_8859-5.vim
/usr/share/vim/vim82/lang/menu_sr_yu.utf-8.vim
/usr/share/vim/vim82/lang/menu_sv.latin1.vim
/usr/share/vim/vim82/lang/menu_sv.utf-8.vim
/usr/share/vim/vim82/lang/menu_sv_se.latin1.vim
/usr/share/vim/vim82/lang/menu_sv_se.utf-8.vim
/usr/share/vim/vim82/lang/menu_tr.cp1254.vim
/usr/share/vim/vim82/lang/menu_tr.iso_8859-9.vim
/usr/share/vim/vim82/lang/menu_tr.utf-8.vim
/usr/share/vim/vim82/lang/menu_tr_tr.cp1254.vim
/usr/share/vim/vim82/lang/menu_tr_tr.iso_8859-9.vim
/usr/share/vim/vim82/lang/menu_tr_tr.utf-8.vim
/usr/share/vim/vim82/lang/menu_uk_ua.cp1251.vim
/usr/share/vim/vim82/lang/menu_uk_ua.koi8-u.vim
/usr/share/vim/vim82/lang/menu_vi_vn.vim
/usr/share/vim/vim82/lang/menu_zh.big5.vim
/usr/share/vim/vim82/lang/menu_zh.cp936.vim
/usr/share/vim/vim82/lang/menu_zh.cp950.vim
/usr/share/vim/vim82/lang/menu_zh.gb2312.vim
/usr/share/vim/vim82/lang/menu_zh_cn.18030.vim
/usr/share/vim/vim82/lang/menu_zh_cn.cp936.vim
/usr/share/vim/vim82/lang/menu_zh_cn.gb2312.vim
/usr/share/vim/vim82/lang/menu_zh_cn.gbk.vim
/usr/share/vim/vim82/lang/menu_zh_cn.utf-8.vim
/usr/share/vim/vim82/lang/menu_zh_tw.big5.vim
/usr/share/vim/vim82/lang/menu_zh_tw.cp950.vim
/usr/share/vim/vim82/lang/menu_zh_tw.utf-8.vim
/usr/share/vim/vim82/lang/nb/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/nl/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/no/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/pl.UTF-8/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/pl.cp1250/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/pl/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/pt_BR/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ru.cp1251/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/ru/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/sk.cp1250/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/sk/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/sr/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/sv/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/tr/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/uk.cp1251/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/uk/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/vi/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/zh_CN.UTF-8/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/zh_CN.cp936/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/zh_CN/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/zh_TW.UTF-8/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/lang/zh_TW/LC_MESSAGES/vim.mo
/usr/share/vim/vim82/macros/README.txt
/usr/share/vim/vim82/macros/editexisting.vim
/usr/share/vim/vim82/macros/hanoi/click.me
/usr/share/vim/vim82/macros/hanoi/hanoi.vim
/usr/share/vim/vim82/macros/hanoi/poster
/usr/share/vim/vim82/macros/justify.vim
/usr/share/vim/vim82/macros/less.bat
/usr/share/vim/vim82/macros/less.sh
/usr/share/vim/vim82/macros/less.vim
/usr/share/vim/vim82/macros/life/click.me
/usr/share/vim/vim82/macros/life/life.vim
/usr/share/vim/vim82/macros/matchit.vim
/usr/share/vim/vim82/macros/maze/Makefile
/usr/share/vim/vim82/macros/maze/README.txt
/usr/share/vim/vim82/macros/maze/maze.c
/usr/share/vim/vim82/macros/maze/maze_5.78
/usr/share/vim/vim82/macros/maze/maze_mac
/usr/share/vim/vim82/macros/maze/mazeansi.c
/usr/share/vim/vim82/macros/maze/mazeclean.c
/usr/share/vim/vim82/macros/maze/poster
/usr/share/vim/vim82/macros/shellmenu.vim
/usr/share/vim/vim82/macros/swapmous.vim
/usr/share/vim/vim82/macros/urm/README.txt
/usr/share/vim/vim82/macros/urm/examples
/usr/share/vim/vim82/macros/urm/urm
/usr/share/vim/vim82/macros/urm/urm.vim
/usr/share/vim/vim82/menu.vim
/usr/share/vim/vim82/mswin.vim
/usr/share/vim/vim82/optwin.vim
/usr/share/vim/vim82/pack/dist/opt/cfilter/plugin/cfilter.vim
/usr/share/vim/vim82/pack/dist/opt/dvorak/dvorak/disable.vim
/usr/share/vim/vim82/pack/dist/opt/dvorak/dvorak/enable.vim
/usr/share/vim/vim82/pack/dist/opt/dvorak/plugin/dvorak.vim
/usr/share/vim/vim82/pack/dist/opt/editexisting/plugin/editexisting.vim
/usr/share/vim/vim82/pack/dist/opt/justify/plugin/justify.vim
/usr/share/vim/vim82/pack/dist/opt/matchit/autoload/matchit.vim
/usr/share/vim/vim82/pack/dist/opt/matchit/doc/matchit.txt
/usr/share/vim/vim82/pack/dist/opt/matchit/doc/tags
/usr/share/vim/vim82/pack/dist/opt/matchit/plugin/matchit.vim
/usr/share/vim/vim82/pack/dist/opt/shellmenu/plugin/shellmenu.vim
/usr/share/vim/vim82/pack/dist/opt/swapmouse/plugin/swapmouse.vim
/usr/share/vim/vim82/pack/dist/opt/termdebug/plugin/termdebug.vim
/usr/share/vim/vim82/plugin/README.txt
/usr/share/vim/vim82/plugin/getscriptPlugin.vim
/usr/share/vim/vim82/plugin/gzip.vim
/usr/share/vim/vim82/plugin/logiPat.vim
/usr/share/vim/vim82/plugin/manpager.vim
/usr/share/vim/vim82/plugin/matchparen.vim
/usr/share/vim/vim82/plugin/netrwPlugin.vim
/usr/share/vim/vim82/plugin/rrhelper.vim
/usr/share/vim/vim82/plugin/spellfile.vim
/usr/share/vim/vim82/plugin/tarPlugin.vim
/usr/share/vim/vim82/plugin/tohtml.vim
/usr/share/vim/vim82/plugin/vimballPlugin.vim
/usr/share/vim/vim82/plugin/zipPlugin.vim
/usr/share/vim/vim82/print/ascii.ps
/usr/share/vim/vim82/print/cidfont.ps
/usr/share/vim/vim82/print/cns_roman.ps
/usr/share/vim/vim82/print/cp1250.ps
/usr/share/vim/vim82/print/cp1251.ps
/usr/share/vim/vim82/print/cp1252.ps
/usr/share/vim/vim82/print/cp1253.ps
/usr/share/vim/vim82/print/cp1254.ps
/usr/share/vim/vim82/print/cp1255.ps
/usr/share/vim/vim82/print/cp1257.ps
/usr/share/vim/vim82/print/dec-mcs.ps
/usr/share/vim/vim82/print/ebcdic-uk.ps
/usr/share/vim/vim82/print/gb_roman.ps
/usr/share/vim/vim82/print/hp-roman8.ps
/usr/share/vim/vim82/print/iso-8859-10.ps
/usr/share/vim/vim82/print/iso-8859-11.ps
/usr/share/vim/vim82/print/iso-8859-13.ps
/usr/share/vim/vim82/print/iso-8859-14.ps
/usr/share/vim/vim82/print/iso-8859-15.ps
/usr/share/vim/vim82/print/iso-8859-2.ps
/usr/share/vim/vim82/print/iso-8859-3.ps
/usr/share/vim/vim82/print/iso-8859-4.ps
/usr/share/vim/vim82/print/iso-8859-5.ps
/usr/share/vim/vim82/print/iso-8859-7.ps
/usr/share/vim/vim82/print/iso-8859-8.ps
/usr/share/vim/vim82/print/iso-8859-9.ps
/usr/share/vim/vim82/print/jis_roman.ps
/usr/share/vim/vim82/print/koi8-r.ps
/usr/share/vim/vim82/print/koi8-u.ps
/usr/share/vim/vim82/print/ks_roman.ps
/usr/share/vim/vim82/print/latin1.ps
/usr/share/vim/vim82/print/mac-roman.ps
/usr/share/vim/vim82/print/prolog.ps
/usr/share/vim/vim82/scripts.vim
/usr/share/vim/vim82/spell/check_locales.vim
/usr/share/vim/vim82/spell/cleanadd.vim
/usr/share/vim/vim82/spell/en.ascii.spl
/usr/share/vim/vim82/spell/en.ascii.sug
/usr/share/vim/vim82/spell/en.latin1.spl
/usr/share/vim/vim82/spell/en.latin1.sug
/usr/share/vim/vim82/spell/en.utf-8.spl
/usr/share/vim/vim82/spell/en.utf-8.sug
/usr/share/vim/vim82/spell/fixdup.vim
/usr/share/vim/vim82/spell/he.vim
/usr/share/vim/vim82/spell/spell.vim
/usr/share/vim/vim82/spell/yi.vim
/usr/share/vim/vim82/synmenu.vim
/usr/share/vim/vim82/syntax/2html.vim
/usr/share/vim/vim82/syntax/8th.vim
/usr/share/vim/vim82/syntax/README.txt
/usr/share/vim/vim82/syntax/a2ps.vim
/usr/share/vim/vim82/syntax/a65.vim
/usr/share/vim/vim82/syntax/aap.vim
/usr/share/vim/vim82/syntax/abap.vim
/usr/share/vim/vim82/syntax/abaqus.vim
/usr/share/vim/vim82/syntax/abc.vim
/usr/share/vim/vim82/syntax/abel.vim
/usr/share/vim/vim82/syntax/acedb.vim
/usr/share/vim/vim82/syntax/ada.vim
/usr/share/vim/vim82/syntax/aflex.vim
/usr/share/vim/vim82/syntax/ahdl.vim
/usr/share/vim/vim82/syntax/aidl.vim
/usr/share/vim/vim82/syntax/alsaconf.vim
/usr/share/vim/vim82/syntax/amiga.vim
/usr/share/vim/vim82/syntax/aml.vim
/usr/share/vim/vim82/syntax/ampl.vim
/usr/share/vim/vim82/syntax/ant.vim
/usr/share/vim/vim82/syntax/antlr.vim
/usr/share/vim/vim82/syntax/apache.vim
/usr/share/vim/vim82/syntax/apachestyle.vim
/usr/share/vim/vim82/syntax/aptconf.vim
/usr/share/vim/vim82/syntax/arch.vim
/usr/share/vim/vim82/syntax/arduino.vim
/usr/share/vim/vim82/syntax/art.vim
/usr/share/vim/vim82/syntax/asciidoc.vim
/usr/share/vim/vim82/syntax/asm.vim
/usr/share/vim/vim82/syntax/asm68k.vim
/usr/share/vim/vim82/syntax/asmh8300.vim
/usr/share/vim/vim82/syntax/asn.vim
/usr/share/vim/vim82/syntax/aspperl.vim
/usr/share/vim/vim82/syntax/aspvbs.vim
/usr/share/vim/vim82/syntax/asterisk.vim
/usr/share/vim/vim82/syntax/asteriskvm.vim
/usr/share/vim/vim82/syntax/atlas.vim
/usr/share/vim/vim82/syntax/autodoc.vim
/usr/share/vim/vim82/syntax/autohotkey.vim
/usr/share/vim/vim82/syntax/autoit.vim
/usr/share/vim/vim82/syntax/automake.vim
/usr/share/vim/vim82/syntax/ave.vim
/usr/share/vim/vim82/syntax/avra.vim
/usr/share/vim/vim82/syntax/awk.vim
/usr/share/vim/vim82/syntax/ayacc.vim
/usr/share/vim/vim82/syntax/b.vim
/usr/share/vim/vim82/syntax/baan.vim
/usr/share/vim/vim82/syntax/bash.vim
/usr/share/vim/vim82/syntax/basic.vim
/usr/share/vim/vim82/syntax/bc.vim
/usr/share/vim/vim82/syntax/bdf.vim
/usr/share/vim/vim82/syntax/bib.vim
/usr/share/vim/vim82/syntax/bindzone.vim
/usr/share/vim/vim82/syntax/blank.vim
/usr/share/vim/vim82/syntax/bsdl.vim
/usr/share/vim/vim82/syntax/bst.vim
/usr/share/vim/vim82/syntax/btm.vim
/usr/share/vim/vim82/syntax/bzl.vim
/usr/share/vim/vim82/syntax/bzr.vim
/usr/share/vim/vim82/syntax/c.vim
/usr/share/vim/vim82/syntax/cabal.vim
/usr/share/vim/vim82/syntax/cabalconfig.vim
/usr/share/vim/vim82/syntax/cabalproject.vim
/usr/share/vim/vim82/syntax/calendar.vim
/usr/share/vim/vim82/syntax/catalog.vim
/usr/share/vim/vim82/syntax/cdl.vim
/usr/share/vim/vim82/syntax/cdrdaoconf.vim
/usr/share/vim/vim82/syntax/cdrtoc.vim
/usr/share/vim/vim82/syntax/cf.vim
/usr/share/vim/vim82/syntax/cfg.vim
/usr/share/vim/vim82/syntax/ch.vim
/usr/share/vim/vim82/syntax/chaiscript.vim
/usr/share/vim/vim82/syntax/change.vim
/usr/share/vim/vim82/syntax/changelog.vim
/usr/share/vim/vim82/syntax/chaskell.vim
/usr/share/vim/vim82/syntax/cheetah.vim
/usr/share/vim/vim82/syntax/chicken.vim
/usr/share/vim/vim82/syntax/chill.vim
/usr/share/vim/vim82/syntax/chordpro.vim
/usr/share/vim/vim82/syntax/cl.vim
/usr/share/vim/vim82/syntax/clean.vim
/usr/share/vim/vim82/syntax/clipper.vim
/usr/share/vim/vim82/syntax/clojure.vim
/usr/share/vim/vim82/syntax/cmake.vim
/usr/share/vim/vim82/syntax/cmod.vim
/usr/share/vim/vim82/syntax/cmusrc.vim
/usr/share/vim/vim82/syntax/cobol.vim
/usr/share/vim/vim82/syntax/coco.vim
/usr/share/vim/vim82/syntax/colortest.vim
/usr/share/vim/vim82/syntax/conaryrecipe.vim
/usr/share/vim/vim82/syntax/conf.vim
/usr/share/vim/vim82/syntax/config.vim
/usr/share/vim/vim82/syntax/context.vim
/usr/share/vim/vim82/syntax/cpp.vim
/usr/share/vim/vim82/syntax/crm.vim
/usr/share/vim/vim82/syntax/crontab.vim
/usr/share/vim/vim82/syntax/cs.vim
/usr/share/vim/vim82/syntax/csc.vim
/usr/share/vim/vim82/syntax/csdl.vim
/usr/share/vim/vim82/syntax/csh.vim
/usr/share/vim/vim82/syntax/csp.vim
/usr/share/vim/vim82/syntax/css.vim
/usr/share/vim/vim82/syntax/cterm.vim
/usr/share/vim/vim82/syntax/ctrlh.vim
/usr/share/vim/vim82/syntax/cucumber.vim
/usr/share/vim/vim82/syntax/cuda.vim
/usr/share/vim/vim82/syntax/cupl.vim
/usr/share/vim/vim82/syntax/cuplsim.vim
/usr/share/vim/vim82/syntax/cvs.vim
/usr/share/vim/vim82/syntax/cvsrc.vim
/usr/share/vim/vim82/syntax/cweb.vim
/usr/share/vim/vim82/syntax/cynlib.vim
/usr/share/vim/vim82/syntax/cynpp.vim
/usr/share/vim/vim82/syntax/d.vim
/usr/share/vim/vim82/syntax/dart.vim
/usr/share/vim/vim82/syntax/datascript.vim
/usr/share/vim/vim82/syntax/dcd.vim
/usr/share/vim/vim82/syntax/dcl.vim
/usr/share/vim/vim82/syntax/debchangelog.vim
/usr/share/vim/vim82/syntax/debcontrol.vim
/usr/share/vim/vim82/syntax/debcopyright.vim
/usr/share/vim/vim82/syntax/debsources.vim
/usr/share/vim/vim82/syntax/def.vim
/usr/share/vim/vim82/syntax/denyhosts.vim
/usr/share/vim/vim82/syntax/desc.vim
/usr/share/vim/vim82/syntax/desktop.vim
/usr/share/vim/vim82/syntax/dictconf.vim
/usr/share/vim/vim82/syntax/dictdconf.vim
/usr/share/vim/vim82/syntax/diff.vim
/usr/share/vim/vim82/syntax/dircolors.vim
/usr/share/vim/vim82/syntax/dirpager.vim
/usr/share/vim/vim82/syntax/diva.vim
/usr/share/vim/vim82/syntax/django.vim
/usr/share/vim/vim82/syntax/dns.vim
/usr/share/vim/vim82/syntax/dnsmasq.vim
/usr/share/vim/vim82/syntax/docbk.vim
/usr/share/vim/vim82/syntax/docbksgml.vim
/usr/share/vim/vim82/syntax/docbkxml.vim
/usr/share/vim/vim82/syntax/dockerfile.vim
/usr/share/vim/vim82/syntax/dosbatch.vim
/usr/share/vim/vim82/syntax/dosini.vim
/usr/share/vim/vim82/syntax/dot.vim
/usr/share/vim/vim82/syntax/doxygen.vim
/usr/share/vim/vim82/syntax/dracula.vim
/usr/share/vim/vim82/syntax/dsl.vim
/usr/share/vim/vim82/syntax/dtd.vim
/usr/share/vim/vim82/syntax/dtml.vim

%files extras-minimal
%defattr(-,root,root,-)
/usr/bin/vim-minimal

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-vim

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vim/100dd019c7d2912226c94666cac0f93eeb82a518
/usr/share/package-licenses/vim/553dde2683f711f77fe79504be0429256223469d
/usr/share/package-licenses/vim/65c71b7ff77a59a32247d83a528728637263c1b5
/usr/share/package-licenses/vim/9979f112bdecefd99762f24f6af76972c2a3a1a6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/da.ISO8859-1/man1/ex.1
/usr/share/man/da.ISO8859-1/man1/rview.1
/usr/share/man/da.ISO8859-1/man1/rvim.1
/usr/share/man/da.ISO8859-1/man1/view.1
/usr/share/man/da.ISO8859-1/man1/vim.1
/usr/share/man/da.ISO8859-1/man1/vimdiff.1
/usr/share/man/da.ISO8859-1/man1/vimtutor.1
/usr/share/man/da.UTF-8/man1/ex.1
/usr/share/man/da.UTF-8/man1/rview.1
/usr/share/man/da.UTF-8/man1/rvim.1
/usr/share/man/da.UTF-8/man1/view.1
/usr/share/man/da.UTF-8/man1/vim.1
/usr/share/man/da.UTF-8/man1/vimdiff.1
/usr/share/man/da.UTF-8/man1/vimtutor.1
/usr/share/man/da/man1/ex.1
/usr/share/man/da/man1/rview.1
/usr/share/man/da/man1/rvim.1
/usr/share/man/da/man1/view.1
/usr/share/man/da/man1/vim.1
/usr/share/man/da/man1/vimdiff.1
/usr/share/man/da/man1/vimtutor.1
/usr/share/man/de.ISO8859-1/man1/ex.1
/usr/share/man/de.ISO8859-1/man1/rview.1
/usr/share/man/de.ISO8859-1/man1/rvim.1
/usr/share/man/de.ISO8859-1/man1/view.1
/usr/share/man/de.ISO8859-1/man1/vim.1
/usr/share/man/de.UTF-8/man1/ex.1
/usr/share/man/de.UTF-8/man1/rview.1
/usr/share/man/de.UTF-8/man1/rvim.1
/usr/share/man/de.UTF-8/man1/view.1
/usr/share/man/de.UTF-8/man1/vim.1
/usr/share/man/de/man1/ex.1
/usr/share/man/de/man1/rview.1
/usr/share/man/de/man1/rvim.1
/usr/share/man/de/man1/view.1
/usr/share/man/de/man1/vim.1
/usr/share/man/fr.ISO8859-1/man1/evim.1
/usr/share/man/fr.ISO8859-1/man1/ex.1
/usr/share/man/fr.ISO8859-1/man1/rview.1
/usr/share/man/fr.ISO8859-1/man1/rvim.1
/usr/share/man/fr.ISO8859-1/man1/view.1
/usr/share/man/fr.ISO8859-1/man1/vim.1
/usr/share/man/fr.ISO8859-1/man1/vimdiff.1
/usr/share/man/fr.ISO8859-1/man1/vimtutor.1
/usr/share/man/fr.ISO8859-1/man1/xxd.1
/usr/share/man/fr.UTF-8/man1/evim.1
/usr/share/man/fr.UTF-8/man1/ex.1
/usr/share/man/fr.UTF-8/man1/rview.1
/usr/share/man/fr.UTF-8/man1/rvim.1
/usr/share/man/fr.UTF-8/man1/view.1
/usr/share/man/fr.UTF-8/man1/vim.1
/usr/share/man/fr.UTF-8/man1/vimdiff.1
/usr/share/man/fr.UTF-8/man1/vimtutor.1
/usr/share/man/fr.UTF-8/man1/xxd.1
/usr/share/man/fr/man1/evim.1
/usr/share/man/fr/man1/ex.1
/usr/share/man/fr/man1/rview.1
/usr/share/man/fr/man1/rvim.1
/usr/share/man/fr/man1/view.1
/usr/share/man/fr/man1/vim.1
/usr/share/man/fr/man1/vimdiff.1
/usr/share/man/fr/man1/vimtutor.1
/usr/share/man/fr/man1/xxd.1
/usr/share/man/it.ISO8859-1/man1/evim.1
/usr/share/man/it.ISO8859-1/man1/ex.1
/usr/share/man/it.ISO8859-1/man1/rview.1
/usr/share/man/it.ISO8859-1/man1/rvim.1
/usr/share/man/it.ISO8859-1/man1/view.1
/usr/share/man/it.ISO8859-1/man1/vim.1
/usr/share/man/it.ISO8859-1/man1/vimdiff.1
/usr/share/man/it.ISO8859-1/man1/vimtutor.1
/usr/share/man/it.ISO8859-1/man1/xxd.1
/usr/share/man/it.UTF-8/man1/evim.1
/usr/share/man/it.UTF-8/man1/ex.1
/usr/share/man/it.UTF-8/man1/rview.1
/usr/share/man/it.UTF-8/man1/rvim.1
/usr/share/man/it.UTF-8/man1/view.1
/usr/share/man/it.UTF-8/man1/vim.1
/usr/share/man/it.UTF-8/man1/vimdiff.1
/usr/share/man/it.UTF-8/man1/vimtutor.1
/usr/share/man/it.UTF-8/man1/xxd.1
/usr/share/man/it/man1/evim.1
/usr/share/man/it/man1/ex.1
/usr/share/man/it/man1/rview.1
/usr/share/man/it/man1/rvim.1
/usr/share/man/it/man1/view.1
/usr/share/man/it/man1/vim.1
/usr/share/man/it/man1/vimdiff.1
/usr/share/man/it/man1/vimtutor.1
/usr/share/man/it/man1/xxd.1
/usr/share/man/ja/man1/evim.1
/usr/share/man/ja/man1/ex.1
/usr/share/man/ja/man1/rview.1
/usr/share/man/ja/man1/rvim.1
/usr/share/man/ja/man1/view.1
/usr/share/man/ja/man1/vim.1
/usr/share/man/ja/man1/vimdiff.1
/usr/share/man/ja/man1/vimtutor.1
/usr/share/man/ja/man1/xxd.1
/usr/share/man/man1/evim.1
/usr/share/man/man1/ex.1
/usr/share/man/man1/rview.1
/usr/share/man/man1/rvim.1
/usr/share/man/man1/view.1
/usr/share/man/man1/vim.1
/usr/share/man/man1/vimdiff.1
/usr/share/man/man1/vimtutor.1
/usr/share/man/man1/xxd.1
/usr/share/man/pl.ISO8859-2/man1/evim.1
/usr/share/man/pl.ISO8859-2/man1/ex.1
/usr/share/man/pl.ISO8859-2/man1/rview.1
/usr/share/man/pl.ISO8859-2/man1/rvim.1
/usr/share/man/pl.ISO8859-2/man1/view.1
/usr/share/man/pl.ISO8859-2/man1/vim.1
/usr/share/man/pl.ISO8859-2/man1/vimdiff.1
/usr/share/man/pl.ISO8859-2/man1/vimtutor.1
/usr/share/man/pl.ISO8859-2/man1/xxd.1
/usr/share/man/pl.UTF-8/man1/evim.1
/usr/share/man/pl.UTF-8/man1/ex.1
/usr/share/man/pl.UTF-8/man1/rview.1
/usr/share/man/pl.UTF-8/man1/rvim.1
/usr/share/man/pl.UTF-8/man1/view.1
/usr/share/man/pl.UTF-8/man1/vim.1
/usr/share/man/pl.UTF-8/man1/vimdiff.1
/usr/share/man/pl.UTF-8/man1/vimtutor.1
/usr/share/man/pl.UTF-8/man1/xxd.1
/usr/share/man/pl/man1/evim.1
/usr/share/man/pl/man1/ex.1
/usr/share/man/pl/man1/rview.1
/usr/share/man/pl/man1/rvim.1
/usr/share/man/pl/man1/view.1
/usr/share/man/pl/man1/vim.1
/usr/share/man/pl/man1/vimdiff.1
/usr/share/man/pl/man1/vimtutor.1
/usr/share/man/pl/man1/xxd.1
/usr/share/man/ru.KOI8-R/man1/evim.1
/usr/share/man/ru.KOI8-R/man1/ex.1
/usr/share/man/ru.KOI8-R/man1/rview.1
/usr/share/man/ru.KOI8-R/man1/rvim.1
/usr/share/man/ru.KOI8-R/man1/view.1
/usr/share/man/ru.KOI8-R/man1/vim.1
/usr/share/man/ru.KOI8-R/man1/vimdiff.1
/usr/share/man/ru.KOI8-R/man1/vimtutor.1
/usr/share/man/ru.KOI8-R/man1/xxd.1
/usr/share/man/ru.UTF-8/man1/evim.1
/usr/share/man/ru.UTF-8/man1/ex.1
/usr/share/man/ru.UTF-8/man1/rview.1
/usr/share/man/ru.UTF-8/man1/rvim.1
/usr/share/man/ru.UTF-8/man1/view.1
/usr/share/man/ru.UTF-8/man1/vim.1
/usr/share/man/ru.UTF-8/man1/vimdiff.1
/usr/share/man/ru.UTF-8/man1/vimtutor.1
/usr/share/man/ru.UTF-8/man1/xxd.1
/usr/share/man/tr.ISO8859-9/man1/evim.1
/usr/share/man/tr.ISO8859-9/man1/ex.1
/usr/share/man/tr.ISO8859-9/man1/rview.1
/usr/share/man/tr.ISO8859-9/man1/rvim.1
/usr/share/man/tr.ISO8859-9/man1/view.1
/usr/share/man/tr.ISO8859-9/man1/vim.1
/usr/share/man/tr.ISO8859-9/man1/vimdiff.1
/usr/share/man/tr.ISO8859-9/man1/vimtutor.1
/usr/share/man/tr.UTF-8/man1/evim.1
/usr/share/man/tr.UTF-8/man1/ex.1
/usr/share/man/tr.UTF-8/man1/rview.1
/usr/share/man/tr.UTF-8/man1/rvim.1
/usr/share/man/tr.UTF-8/man1/view.1
/usr/share/man/tr.UTF-8/man1/vim.1
/usr/share/man/tr.UTF-8/man1/vimdiff.1
/usr/share/man/tr.UTF-8/man1/vimtutor.1
/usr/share/man/tr/man1/evim.1
/usr/share/man/tr/man1/ex.1
/usr/share/man/tr/man1/rview.1
/usr/share/man/tr/man1/rvim.1
/usr/share/man/tr/man1/view.1
/usr/share/man/tr/man1/vim.1
/usr/share/man/tr/man1/vimdiff.1
/usr/share/man/tr/man1/vimtutor.1
