#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vim
Version  : 8.0.1655
Release  : 322
URL      : https://github.com/vim/vim/archive/v8.0.1655.tar.gz
Source0  : https://github.com/vim/vim/archive/v8.0.1655.tar.gz
Summary  : Abstract VT220/Xterm/ECMA-48 emulation library
Group    : Development/Tools
License  : MIT Vim
BuildRequires : gmp-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : python-dev
BuildRequires : python3-dev
Patch1: stateless.patch
Patch2: 0001-add-clearlinux-vimrc-file.patch

%description
This is a MODIFIED version of libvterm.
The original can be found:
- on the original site (tar archive and Bazaar repository):
http://www.leonerd.org.uk/code/libvterm/
- cloned on Github:
https://github.com/neovim/libvterm

%prep
%setup -q -n vim-8.0.1655
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522373101
%configure --disable-static --with-features=huge  --with-tlib=ncurses  --enable-gtk2-check --enable-gui=gtk2 --enable-cscope --enable-multibyte --enable-luainterp --enable-pythoninterp --enable-cscope  --enable-python3interp
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1522373101
rm -rf %{buildroot}
%make_install
## make_install_append content
ln -s vim %{buildroot}/usr/bin/vi
install -p -D -m 644 vimrc %{buildroot}/usr/share/vim/
## make_install_append end

%files
%defattr(-,root,root,-)
